//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROGADUN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchID { get; set; }
        public string Name { get; set; }
        public int IdArena { get; set; }
        public System.DateTime DateEvent { get; set; }
        public string Guest { get; set; }
        public string Score { get; set; }
    
        public virtual Arena Arena { get; set; }
    }
}
