//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROGADUN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShip
    {
        public int MembershipID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBrth { get; set; }
        public int IdRole { get; set; }
        public int Age { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
