//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROGADUN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otchet
    {
        public int OtchetID { get; set; }
        public Nullable<int> IdMatch { get; set; }
    }
}
